### ISSUE TITLE
People-Magazine > Timeline

### ISSUE THREAD

**Issue by Prev** [memento7/service-frontend#4]
- [x] Listing
- [x] Show image
    - [x] Thumbnail
- [x] Show emotions
    - [x] Color presets
- [x] Show issue_score
    - [x] Calculate by relative score
- [x] Dropdown list
    - [x] Get filtered timeline in API Server

**Comment by jiunbae** [comment]
The color of timeline left-bar are very vague.
plz, do not use random.
These are hinders UX.
